'''
biomem Localization Module.
Handles user-facing strings for Dashboard, CLI, and Tray Icon.
'''
import logging

logger = logging.getLogger('bdbm.localization')


class Localization:
    _strings = {
        "en": {
            "nav.chat": "CHAT",
            "nav.module": "MODULE",
            "nav.memory": "MEMORY",
            "nav.llm_settings": "LLM SETTINGS",
            "nav.news": "NEWS",
            "ui.title_sub": "private memory across all your AI models",
            "ui.model": "Model",
            "ui.new_chat": "+ New Chat",
            "ui.recent_chats": "Recent Chats",
            "ui.memory": "Memory",
            "ui.ltm": "LTM: ",
            "ui.stm": "STM: ",
            "ui.fatigue": "Fatigue: ",
            "ui.loading_model": "⏳ Loading language model…",
            "ui.loading_model_detail": "This may take 1-2 minutes on first launch.",
            "ui.writes": "Writes",
            "ui.reads": "Reads",
            "ui.fatigue_label": "Fatigue",
            "ui.select_history": "Select history file",
            "ui.text_files": "Text files",
            "ui.all_files": "All files",
            "ui.filter_images": "Images",
            "ui.filter_pdf": "PDF",
            "ui.filter_text": "Text files",
            "ui.filter_all": "All supported",
            "ui.default": "Default",
            "ui.starting": "Starting…",
            "ui.ready": "READY",
            "ui.options": "Options",
            "ui.deep_recall": "Deep Recall",
            "ui.deep_recall_tip": "Recall related thoughts from LTM during conversation",
            "ui.web_search": "Web Search",
            "ui.web_search_tip": "Augment conversation with real-time web results",
            "ui.type_message": "Type a message...",
            "ui.send": "➤",
            "ui.attach": "Attach Files",
            "ui.rename": "Rename",
            "ui.delete": "Delete",
            "ui.error": "Error",
            "ui.clear_all": "Clear All",
            "ui.close": "Close",
            "ui.thinking": "Thinking",
            "ui.remembering": "Remembering",
            "ui.boondoggling": "Boondoggling",
            "ui.shifting": "Shifting",
            "ui.seriousing": "Seriousing",
            "module.status_title": "Module Status",
            "module.ltm_label": "LTM: {} / {}",
            "module.stm_label": "STM: {} / {}",
            "module.stats_label": "Writes: {} | Reads: {}",
            "module.backup": "Backup",
            "module.restore": "Restore",
            "module.shutdown": "Shutdown",
            "module.shutdown_hint": "Closing this window keeps biomem running in the background (see the system tray icon). To fully exit, use the Shutdown button below.",
            "memory.title": "Memory Management",
            "memory.legacy_import_hint": "⚠️ Have a legacy .pt memory file? Import it now — this option will be locked after the first new write.",
            "memory.import_pt": "Import .pt",
            "memory.clear_stm": "Clear STM",
            "memory.clear_all": "Clear LTM + STM",
            "memory.refactor": "Rebuild Cognitive Terrain",
            "memory.refactor_title": "Cognitive Terrain Rebuild",
            "memory.refactor_progress": "Replaying record {}/{}...",
            "memory.refactor_step_backup": "Creating safety backup...",
            "memory.refactor_step_collect": "Collecting memory records...",
            "memory.refactor_step_reset": "Resetting memory...",
            "memory.refactor_step_replay": "Replaying records...",
            "memory.refactor_step_verify": "Verifying integrity...",
            "memory.refactor_success": "Cognitive Terrain Rebuild completed successfully!\n{} records replayed\nSTM: {} centers | LTM: {} centers\nVerification: {:.0%}",
            "memory.refactor_failed": "Cognitive Terrain Rebuild failed. Memory has been restored from backup.\nError: {}",
            "memory.export_product": "Export Practice-as-a-Product",
            "memory.export_report": "Generate biomem Passport (.pdf)",
            "memory.export_report_hint": "Creates a mathematically verified biomem Passport (PDF) overview of memory contents and semantic domains.",
            "memory.paap_desc": "Transform your accumulated long-term memory and cognitive terrain into a portable, standalone archive for deployment or sharing.",
            "memory.paap_badge": "PORTABLE EXPORT",
            "memory.card_viz_title": "Visualizations & Cognitive Maps",
            "memory.card_viz_desc": "Interactive analytical tools for exploring semantic clusters, hierarchical relationships, and temporal development of memory centres.",
            "memory.card_params_title": "Homeostasis & Storage Thresholds",
            "memory.card_params_desc": "Real-time stabilization settings controlling consolidation limits, activation decay, and maximum capacity.",
            "memory.card_maint_title": "Maintenance & Operations",
            "memory.card_maint_desc": "Essential operational actions for memory maintenance, structural rebuild, and targeted cleansing.",
            "memory.refactor_subtitle": "Rebuilds 3D terrain and regenerates all associations based on historical ages.",
            "memory.clear_subtitle": "Clears memory buffers and resets all stored centers.",
            "memory.show_dendrogram": "Show Memory Dendrogram",
            "memory.select_source": "Memory source:",
            "memory.dendrogram_title": "Semantic Memory Map",
            "memory.dendrogram_subtitle": "Hierarchical clustering of LTM memory centres (Ward method)",
            "memory.dendrogram_refresh": "Refresh",
            "memory.dendrogram_empty": "Not enough data. At least 2 active LTM centres are required.",
            "memory.dendrogram_error": "Failed to compute dendrogram: {}",
            "memory.dendrogram_centers": "{} LTM centres",
            "memory.dendrogram_usage": "Reading frequency",
            "memory.dendrogram_thick_label": "Line thickness:",
            "memory.dendrogram_thick_uniform": "Standard (uniform)",
            "memory.dendrogram_thick_intensity": "Storage intensity",
            "memory.dendrogram_thick_frequency": "Reading frequency",
            "memory.dendrogram_thick_combined": "Combined (Intensity × Frequency)",
            "memory.dendrogram_color_thresh": "Color threshold:",
            "memory.show_temporal": "Show Temporal Evolution Map",
            "memory.temporal_title": "Cognitive Temporal Evolution Map",
            "memory.temporal_subtitle": "Spatiotemporal mapping of LTM centres (Semantics × Age, Outlier preservation)",
            "memory.temporal_refresh": "Refresh",
            "memory.temporal_empty": "Not enough data. At least 2 active LTM centres are required.",
            "memory.temporal_error": "Failed to compute temporal evolution map: {}",
            "memory.temporal_centers": "{} LTM centres",
            "memory.temporal_view_label": "View mode:",
            "memory.temporal_view_macro": "Macro (Semantic Streams / Swimlanes)",
            "memory.temporal_view_micro": "Micro (Individual LTM centres)",
            "memory.temporal_lanes_label": "Swimlanes:",
            "memory.temporal_lanes_auto": "Auto (7 lanes)",
            "memory.temporal_reset_zoom": "Reset Zoom & Pan",
            "memory.show_graph": "Show Semantic Map",
            "memory.graph_title": "Semantic Memory Graph",
            "memory.graph_subtitle": "Network graph of centres and their associations by semantic similarity",
            "memory.graph_min_sim": "Min. similarity:",
            "memory.graph_refresh": "Refresh",
            "memory.graph_empty": "Not enough data for graph view.",
            "memory.graph_error": "Error loading map: {}",
            "memory.center_title": "Memory Centre #{}",
            "memory.center_key": "Key text",
            "memory.center_value": "Stored text",
            "memory.center_intensity": "Intensity",
            "memory.center_usage": "Access count",
            "memory.center_save": "Save changes",
            "memory.center_delete": "Delete centre",
            "memory.center_confirm_delete": "Delete centre #{}? This action is irreversible.",
            "memory.center_saved": "Saved.",
            "memory.center_deleted": "Centre deleted.",
            "memory.center_empty": "(empty)",
            "memory.center_loading": "Loading...",
            "memory.center_error": "Error: {}",
            "memory.center_refactor_hint": "💡 Tip: After editing or deleting centers, it is advisable to rebuild cognitive terrain.",
            "memory.advanced_warning": "⚠️ Advanced settings — use only if you know what you are doing.",
            "memory.max_associations": "Max associations sent to model",
            "memory.stm_threshold": "STM new center threshold",
            "memory.ltm_threshold": "LTM consolidation threshold (new centers)",
            "memory.reset_defaults": "Restore defaults",
            "memory.effect_desc": "<b>STM vs. LTM:</b> STM threshold applies immediately upon direct write. LTM threshold applies during sleep/consolidation, determining the degree of topic merging.<br><br><b>Effect of decreasing:</b> New centers are created only for sufficiently distinct information, making new memory formation less likely. Most interactions are therefore merged into existing centers. This results in a more conservative system that relies on established knowledge and is less willing to accept new information.<br><br><b>Effect of increasing:</b> New centers are created even for slightly different information, causing capacity to fill more quickly. The system becomes more receptive to new inputs, but may also store many near-duplicate variants of the same information unless protected by a sufficiently strong “safety net.”",
            "llm.title": "LLM Settings",
            "llm.subtitle": "Enter your own API keys (BYOK – Bring Your Own Key). Keys are stored encrypted with your hardware fingerprint.",
            "llm.get_api_key": "Get API key",
            "llm.save_settings": "Save LLM Settings",
            "llm.api_key": "API Key",
            "llm.ollama_url": "Ollama URL",
            "llm.model_name": "Model name",
            "llm.context_window": "Context window",
            "llm.disabled": "Disabled",
            "llm.words": "words",
            "llm.request_timeout": "Request timeout",
            "llm.min": "min",
            "llm.system_prompt": "System Prompt / Personalisation",
            "llm.local": "Local",
            "llm.placeholder_key": "Enter {} API key…",
            "llm.placeholder_personal": "Optional: custom instructions for this model (e.g. 'Answer in Czech. Be concise.')",
            "news.title": "News",
            "msg.new_chat_started": "New conversation started. Memory context preserved.",
            "msg.delete_thread_confirm": "Are you sure you want to delete this conversation?",
            "msg.delete_thread_title": "Delete Thread",
            "msg.rename_thread_title": "Rename thread",
            "msg.new_name": "New name:",
            "msg.backup_done": "Backup created:\n{}",
            "msg.restore_done": "Memory successfully restored from backup.",
            "msg.export_done": "Practice-as-a-Product exported:\n{}",
            "msg.report_success": "biomem Passport successfully generated at:\n{}",
            "msg.report_failed": "Failed to generate biomem Passport:\n{}",
            "msg.import_failed_read": "Could not read file: {}",
            "msg.import_no_pairs": "No conversation pairs found in the file.\nExpected format:\nUser: ...\nModel: ...",
            "msg.import_started": "Importing {} conversation pairs into biomem memory.\nThis may take a moment.",
            "msg.save_success": "Settings saved successfully.",
            "msg.pam_warning_html": "⚠️ <b>The model did not follow the memory token format correctly.</b><br><span style='font-size:12px;'>This can happen with smaller local models running via Ollama. Try lowering the model's temperature setting. If it keeps happening, type <i>'respect PAM tokens'</i> in your next message to remind the model.</span>",
            "msg.not_ready_err": "⛔ biomem module not ready yet. Please wait.",
            "msg.restore_confirm": "Are you sure you want to restore memory from backup?\nCurrent state will be automatically backed up.",
            "msg.shutdown_confirm": "Are you sure you want to shut down the biomem memory module?",
            "msg.shutdown_title": "Shut Down Module",
            "msg.clear_stm_confirm": "Are you sure you want to clear short-term memory?",
            "msg.clear_all_confirm": "Are you sure you want to clear ALL memory (LTM + STM)?",
            "msg.refactor_confirm": "Are you sure you want to rebuild cognitive terrain?\nThis process will safely reorganize your records and regenerate 3D landscape.",
            "msg.import_blocked_title": "Import Blocked",
            "msg.import_blocked_msg": "Legacy .pt import is only available before the first new write to memory.",
            "msg.already_running": "biomem memory module is already running.\n\nAnother instance is listening on 127.0.0.1:8765.\nOnly one instance can run at a time.",
            "msg.failed_to_start": "Failed to start the module.",
            "wizard.title": "Welcome to biomem — Setup",
            "wizard.welcome": "<b>Welcome to biomem!</b><br>Let's personalise your experience in a few quick steps.",
            "wizard.name": "Your name:",
            "wizard.name_placeholder": "e.g. John Doe",
            "wizard.profession": "Profession / role:",
            "wizard.profession_placeholder": "e.g. Software developer, Researcher, Student…",
            "wizard.goal": "Main goal:",
            "wizard.goal_placeholder": "e.g. Learn machine learning, Build a startup…",
            "wizard.import_title": "<b>Optional:</b> Import an existing conversation history (.txt)",
            "wizard.no_file": "No file selected",
            "wizard.browse": "Browse…",
            "tray.title": "biomem memory module",
            "tray.dashboard": "Dashboard",
            "tray.quit": "Quit",
            "tray.running": "biomem memory module – Running",
            "cli.desc": "Memory Module CLI - Text in/out memory system",
            "cli.help_state": "Path to memory state file",
            "cli.help_device": "Device (cpu/cuda, default: auto)",
            "cli.help_no_load": "Do not load existing state",
            "cli.cmd_store": "Store key-value pair",
            "cli.cmd_recall": "Recall text from memory",
            "cli.cmd_stats": "Display statistics",
            "cli.cmd_consolidate": "Force STM->LTM consolidation",
            "cli.cmd_reset": "Reset memory",
            "cli.cmd_interactive": "Interactive mode",
            "cli.cmd_batch": "Batch load from file",
            "cli.cmd_list": "List stored memories",
            "cli.cmd_forget": "Forget memories",
            "cli.cmd_edit": "Edit memory value",
            "cli.cmd_search": "Search memories",
            "cli.stored_success": "Stored: '{}' -> '{}'",
            "cli.new_centers": "   New centers: {}",
            "cli.not_found": "Not found",
            "cli.result": "Result: {}",
            "cli.key": "   Key: {}",
            "cli.confidence": "   Confidence: {:.3f}",
            "cli.source": "   Source: {}",
            "cli.found_n": "Found {} memories",
            "cli.stats_title": "Memory Statistics:",
            "cli.ltm_stats": "   LTM: {}/{} centers ({} texts)",
            "cli.stm_stats": "   STM: {}/{} centers ({} texts)",
            "cli.writes": "   Writes: {}",
            "cli.reads": "   Reads: {}",
            "cli.consolidations": "   Consolidations: {}",
            "cli.steps": "   Steps: {}",
            "cli.fatigue": "   Fatigue: {:.1%}",
            "cli.device": "   Device: {}",
            "cli.consolidate_done": "Consolidation complete:",
            "cli.transferred": "   Transferred: {} centers",
            "cli.new_ltm": "   New LTM: {}",
            "cli.host": "Host for WS server (default: 127.0.0.1)",
            "cli.port": "Port for WS server (default: 8765)",
            "cli.data_dir": "Data directory (default: auto ~/.bdbm/ or %%LOCALAPPDATA%%/biomem/)",
            "cli.state_file": "Path to state file (default: <data-dir>/memory_state.bdbm)",
            "cli.debug": "Enable debug logging (console mode without GUI)",
            "cli.no_tray": "Do not show system tray icon",
            "cli.no_gui": "Run without Dashboard GUI (headless/legacy mode)",
            "cli.version": "Show version and exit",
            "cli.already_running": "biomem memory module is already running.\n\nAnother instance is listening on {}:{}.\nOnly one instance can run at a time.",
            "cli.error_fatal": "Fatal error in background thread: {}",
            "cli.error_start": "Failed to start",
            "cli.legacy_found": "Found legacy state {}, will be migrated to .bdbm",
            "cli.model_ready": "Model loaded and ready.",
            "cli.migration_done": "Migration .pt -> .bdbm complete: {}",
            "cli.migration_failed": "Migration .pt -> .bdbm failed: {}",
            "cli.install_deps": "   Install: pip install websockets>=12.0 cryptography>=41.0",
            "cli.error_init": "Error during initialization: {}",
            "cli.headless_switch": "Dashboard unavailable. Switching to headless mode.",
            "cli.reset_warning": "This will delete all data! Use --confirm to verify.",
            "cli.reset_done": "Memory reset",
            "cli.interactive_welcome": "Memory Module - Interactive Mode",
            "cli.interactive_help": "   Commands: store <key> | <value>\n           recall <query>\n           stats | consolidate | save | quit",
            "cli.goodbye": "Goodbye!",
            "cli.empty": "Memory is empty",
            "cli.search_results": "Found {} results:",
            "cli.stored_success_short": "Stored ({} new centers)",
            "cli.interactive_format_err": "Format: store key | value",
            "cli.cmd_unknown": "I don't understand the command '{}'",
            "cli.file_not_found": "File does not exist: {}",
            "cli.batch_loaded": "Loaded {} items from {}",
            "cli.not_found_err": "No memory found",
            "cli.step_done": "Homeostasis step performed",
            "cli.arg_key": "Key (text)",
            "cli.arg_value": "Value (text)",
            "cli.arg_emotion": "Emotional context",
            "cli.arg_intensity": "Storage intensity (0.0-2.0)",
            "cli.arg_query": "Query (text)",
            "cli.arg_top_k": "Number of candidates",
            "cli.arg_file": "Path to file (format: key<tab>value)",
            "cli.arg_separator": "Separator (default: tab)",
            "cli.arg_source": "Memory source",
            "cli.arg_limit": "Max items",
            "cli.arg_pattern": "Key text to forget",
            "cli.arg_exact": "Exact key match",
            "cli.arg_old_val": "Original value text",
            "cli.arg_new_val": "New value text",
            "cli.arg_search_query": "Search text",
            "cli.arg_search_limit": "Number of results",
            "report.title": "biomem Passport",
            "report.subtitle": "Technical Passport & Knowledge Terrain Certificate (biomem)",
            "report.badge": "PRACTICE-AS-A-PRODUCT CERTIFIED",
            "report.sec1_title": "1. Cognitive Passport & Summary Indicators",
            "report.sec1_th_param": "Parameter / Indicator",
            "report.sec1_th_val": "Value",
            "report.sec1_th_desc": "Methodological Significance",
            "report.sec1_ltm_param": "<b>Total Centres in LTM</b> (Long-Term Memory)",
            "report.sec1_ltm_desc": "Consolidated, semantically anchored and structured knowledge units.",
            "report.sec1_stm_param": "<b>Records in STM</b> (Short-Term Buffer)",
            "report.sec1_stm_desc": "Newly ingested, yet unconsolidated information awaiting sleep cycles.",
            "report.sec1_ratio_param": "<b>Cognitive Maturity Index</b> (Consolidation Ratio)",
            "report.sec1_ratio_desc": "Proportion of permanently retained centres out of total memory volume.",
            "report.sec1_int_param": "<b>Average Storage Intensity</b>",
            "report.sec1_int_desc": "Resistance level against forgetting and semantic specificity.",
            "report.sec1_acc_param": "<b>Average Access Count</b>",
            "report.sec1_acc_desc": "Vitality and active practical utility of stored know-how.",
            "report.sec1_ops_param": "<b>Historical Operation Turnover</b> (Read / Write / Consolidation)",
            "report.sec1_ops_desc": "Total read queries performed, direct writes, and homeostasis cycles.",
            "report.sec2_title": "2. Knowledge Domains & Semantic Taxonomy",
            "report.sec2_desc": "Automated identification of core thematic clusters via Ward hierarchical clustering over cosine distance matrix with algorithmic keyword extraction.",
            "report.sec2_th_domain": "Domain",
            "report.sec2_th_keywords": "Core Keywords (Semantic Profile)",
            "report.sec2_th_share": "Memory Share",
            "report.sec2_th_int": "Avg. Intensity",
            "report.sec2_domain_idx": "Domain #{}",
            "report.sec2_centers_count": "{} centres",
            "report.sec2_empty": "Insufficient data to divide into domain clusters.",
            "report.sec3_title": "3. Structural Topology & Semantic Cohesion",
            "report.sec3_th_metric": "Network Metric",
            "report.sec3_th_state": "State & Interpretation",
            "report.sec3_density_param": "<b>Semantic Network Density (Graph Density)</b><br><span style='font-size: 8.5pt; color: #64748b;'>Cosine similarity threshold ≥ 0.55</span>",
            "report.clustering": "<b>Clustering Coefficient</b><br><span style='font-size: 8.5pt; color: #64748b;'>Measure of cognitive bubble closure</span>",
            "report.drift": "<b>Semantic Drift (Centroid Shift)</b><br><span style='font-size: 8.5pt; color: #64748b;'>Spatiotemporal deformation of the vector space</span>",
            "report.drift_nodata": "Insufficient vector data",
            "report.drift_min_data": "Insufficient data to measure drift (min. 5 memories)",
            "report.drift_stable": "Stable (negligible semantic shift)",
            "report.drift_incremental": "Moderate development (incremental knowledge evolution)",
            "report.drift_dynamic": "Dynamic development (significant shift in memory centroid)",
            "report.eigenvector": "Most Influential Nodes - Eigenvector Centrality (Grey Eminences):",
            "report.sec3_th_score": "Centrality Score",
            "report.sec3_hubs_title": "Top Semantic Bridges (Centres with highest cross-connectivity):",
            "report.sec3_th_id": "Centre ID",
            "report.sec3_th_conns": "Strong Connections",
            "report.sec3_th_preview": "Content Preview / Key Text",
            "report.sec3_conns_count": "{} connections",
            "report.sec4_title": "4. Knowledge Terrain Hierarchical Map (Ward Dendrogram)",
            "report.sec4_caption": "Hierarchical clustering structure of LTM centres (Ward method over cosine distance matrix)",
            "report.sec5_title": "{}. Top 10 Most Valuable Cognitive Anchors",
            "report.sec5_desc": "Centres with the highest combined retention and practical utilization value (Score = Intensity × log(1 + Access Count)).",
            "report.sec5_th_rank": "Rank",
            "report.sec5_th_id": "Centre ID",
            "report.sec5_th_score": "Intensity / Reads",
            "report.sec5_th_text": "Record Key Text",
            "report.sec5_empty": "No centres currently stored in long-term memory.",
            "report.footer": "Generated by <b>biomem (Neural Cognitive Memory)</b> on {} &nbsp;|&nbsp; Purely Algorithmic Report (Zero-Hallucination & Math-Verified) &nbsp;|&nbsp; Practice-as-a-Product Module",
            "report.density_high": "High (Cohesive Expert Network)",
            "report.density_medium": "Medium (Structured Domain Connectivity)",
            "report.density_low_spec": "Low (Isolated Specificity of Records)",
            "report.density_low_iso": "Low (Isolated Records)",
            "report.general_content": "General Cognitive Content",
            "report.center_id": "Centre #{}",
            "report.dendrogram_chart_title": "Centre Hierarchical Taxonomy (Ward Method over Cosine Matrix)",
        },
    }

    _lang = 'en'

    @classmethod
    def set_language(cls, lang: str):
        if lang in cls._strings:
            cls._lang = lang
            logger.info('Language set to: %s', lang)

    @classmethod
    def get(cls, key: str, *args, default: str = None) -> str:
        s = cls._strings.get(cls._lang, {}).get(key, default or key)
        if args:
            try:
                return s.format(*args)
            except Exception as e:
                logger.error("Localization formatting error for key '%s': %s", key, e)
        return s


T = Localization.get
